Experiment_name: ntu_bone_xsub

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu60_smpl/xsub/bone_data/h5_data_118/train/
  label_path: ./data/ntu60_smpl/xsub/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu60_smpl/xsub/bone_data/h5_data_118/test/
  label_path: ./data/ntu60_smpl/xsub/test_label.pkl

# model
model: model.decouple_gcn.Model
model_args:
  num_class: 60
  num_point: 67
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  groups: 16
  block_size: 41
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [60, 80]

# training
device: [0,1,2,3]
keep_rate: 0.9
only_train_epoch: 1
batch_size: 64
test_batch_size: 64
num_epoch: 100
nesterov: True
